RT-59 Smoke test for test harness
nhsconnect/integration-adaptors pull request #24
Opened 2019-07-02 07:40 UTC by PhilSmithBJSS

2019-07-02 10:50 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/page_objects/build_scr.py
> +from utilities.message_utilities import MessageUtilities
As we're following the google standards I think we're trying to avoid importing specific classes in favor of importing the whole module.

2019-07-02 10:50 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/page_objects/build_scr.py
> +        "Id": MessageUtilities.get_uuid(),
Might be worth moving this dictionary to a json file in the data folder and loading it with JSON.loads (think there is  a json loading method in the utilities package). Then just update the variables we receive as parameters as needed.

2019-07-02 10:50 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/page_objects/interactions.py
> +        return str(e)
Is there anything specific this Exception is trying to catch that we can use instead of a catch all statement?

2019-07-02 10:50 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/page_objects/xml_parser.py
> +import xml.etree.ElementTree as ET
`ET` probably wants to be lower case I think

2019-07-02 10:50 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/test_scenarios/test_smoke_test.py
> +
Again, import the modules over specific classes within the modules

2019-07-02 10:50 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/page_objects/build_scr.py
> +    :param human_readable_payload: The himan readable payload to be included in the summary message.
small but there's a typo here

2019-07-02 10:50 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/data/local_asid
> +918999199091
You mention later in a comment that this should be excluded from git

2019-07-02 10:50 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/page_objects/methods.py
> +
There is a method in the `FileUtilities` class that will handle this file reading, might be worth extracting the file path into a constant. Previously we using the `Path` library to build paths and there is also a `ROOT_DIR` constant in the `definitions` module that we used as a reference point

2019-07-02 10:50 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/page_objects/methods.py
> +    self.driver = driver
Is this method needed? There is no class surrounding these methods

2019-07-02 10:50 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/test_scenarios/test_smoke_test.py
> +        self.parser = XmlMessageParser()
This member variable doesn't seem to be used anywhere?

2019-07-02 13:45 UTC, ismail-s requested changes
I don't think the file ` mhs-reference-implementation/selenium_tests/data/__init__.py` needs to be there.

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/data/local_asid
> +918999199091
I don't think this should have been committed.

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/Pipfile
> +scr = {editable = true,path = "./../SCR"}
I think this makes sense to do, though I don't know as much about the repo structure as @gareth-allan.

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/templates/index.html
> +{% extends "layout.html" %}
Is this file being used anywhere?

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/build_scr.py
> +from src.gp_summary_update import SummaryCareRecord
```suggestion
from scr.gp_summary_update import SummaryCareRecord
```

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/test_scenarios/test_smoke_test.py
> +        self.parser = XmlMessageParser()
This parser is unused

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/test_scenarios/test_smoke_test.py
> +            methods.get_interaction(interaction_name, nhs_number)), "Happy path test failed")
Minor/optional: This line feels a bit chunky, maybe break into separate lines with variables?

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/methods.py
> +def __init__(self, driver):
Unused method

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/methods.py
> +    ###The asid should be stored in data\local_asid file (which is excluded from GIT
The last part currently doesn't seem to be true

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/methods.py
> +    with open(os.path.join(os.getcwd(), "selenium_tests\\data\\local_asid")) as asid_file:
I think this line could be better as:
```suggestion
    with (Path(ROOT_DIR) / "selenium_tests" / "data" / "local_asid").open() as asid_file:
```

or instead of the whole with statement, you could do [`asid = (Path('blah' / ...).read_text()`](https://github.com/python/cpython/blob/d5c120f7eb6f2a9cdab282a5d588afed307a23df/Lib/pathlib.py#L1204) though that might include a newline on the end.

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/methods.py
> +    asid_file.close()
Don't need this line, the with statement does this for you

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/methods.py
> +    returned_data = xml_parser.XmlMessageParser().parse_message(returned_xml)
The `xml_parser.XmlMessageParser()` part can be extracted into a variable.

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/interactions.py
> +Routes and views for the flask application.
This docstring doesn't seem correct.

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/interactions.py
> +        return str(e)
Why catch the exception like this, if this is a test?

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/build_scr.py
> +import datetime
So this file is the same as the file in supplier_example. I'm not sure if that's an issue or not, in my head I feel like it isn't as that's just some example POC thingy and this is the actual deliverable thing (hopefully).

2019-07-02 13:45 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/xml_parser.py
> +CONTROLACTEVENT = "classCode"
What does the _ACT_ mean, is that action or something else?

2019-07-05 09:28 UTC, ismail-s commented on mhs-reference-implementation/README.md
> -`pipenv run tests` will run all tests.
Optional: perhaps we could still have a `pipenv run tests` if we want to run unit and integration tests together?

2019-07-05 09:28 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/data/local_asid
> -918999199091
Also need gitignore to be updated

2019-07-05 09:28 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/message_builder.py
> +        """Create a new JSONMessageBuilder that uses a json request template file.
Not sure JSONMessageBuilder is the correct word here

2019-07-05 09:28 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/message_builder.py
> +    """A component that uses Pystache to populate a Mustache template in order to build a json message."""
Don't think you are using this class to build a json message

2019-07-05 09:28 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/xml_parser.py
> +import xml.etree.ElementTree as et
Minor/optional: I think `ET` was better, or at least, [more standard](https://docs.python.org/3/library/xml.etree.elementtree.html#tutorial)

2019-07-05 09:28 UTC, ismail-s commented on mhs-reference-implementation/Pipfile
> +scr = {editable = true,path = "./../SCR"}
Is this import still being used?

2019-07-05 09:46 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/page_objects/xml_parser.py
> +import xml.etree.ElementTree as et
Pycharm will highlight this as non standard import format, and in a previous review I think it was mentioned that capitals imply class names. Arguably ElementTree doesn't follow the naming standards we're using so I don't know which is more appropriate, like you say though, very minor!

2019-07-05 09:48 UTC, Philip-Woods commented on mhs-reference-implementation/selenium_tests/page_objects/message_builder.py
> +        super().__init__(template_dir, template_file)
Is there any particular reason this is using a whole new class vs a regular instance of `PystacheMessageBuilder`?

2019-07-05 11:50 UTC, ismail-s commented on mhs-reference-implementation/Pipfile
> -scr = {editable = true,path = "./../SCR"}
Can you also regenerate the lockfile

2019-07-08 07:22 UTC, PhilSmithBJSS commented on mhs-reference-implementation/selenium_tests/page_objects/xml_parser.py
> +import xml.etree.ElementTree as et
ElementTree no longer used, so we can save this discussion for another time...

2019-07-08 07:26 UTC, PhilSmithBJSS commented on mhs-reference-implementation/README.md
> -`pipenv run tests` will run all tests.
Chaining commands in pipenv is not available.  To do this would necessitate the use of '&&' or similar, depending on the operating system.

2019-07-08 08:36 UTC, ismail-s requested changes
Still need gitignore to be updated

2019-07-08 08:36 UTC, ismail-s commented on mhs-reference-implementation/selenium_tests/page_objects/xml_parser.py
> +import xml.etree.ElementTree as et
Don't think that's true, you're still using it. In any case, I'm not pushing this point, I marked it as minor/optional.

2019-07-08 08:50 UTC, ismail-s approved these changes

2019-07-08 08:53 UTC, merged