[WIP] NIAD-155 outbound sequence number manager record send
nhsconnect/integration-adaptors pull request #243
Opened 2020-05-04 06:24 UTC by Alicja-Kainos

2020-05-05 09:04 UTC, grzegorz-robak submitted a review, later dismissed

2020-05-05 09:04 UTC, grzegorz-robak commented on nhais/outbound/state/work_description.py
> +        Attempts to publish the local state of the work description to the state store, checks versions to avoid
At what point it checks version?

2020-05-05 09:04 UTC, grzegorz-robak commented on nhais/outbound/state/work_description.py
> +        raise ValueError('Expected persistence store to not be None')
The same check is done in `WorkDescription` constructor

2020-05-05 09:10 UTC, Alicja-Kainos commented on nhais/outbound/state/work_description.py
> +        raise ValueError('Expected persistence store to not be None')
right, it should be removed from one place :)

2020-05-05 09:11 UTC, Alicja-Kainos commented on nhais/outbound/state/work_description.py
> +        Attempts to publish the local state of the work description to the state store, checks versions to avoid
That is the case: I did not want to use the version checking like in MHS (get, than update). Anyway, the scope of the task is to save the state, not doing update, if I got it right :)

2020-05-05 09:13 UTC, Alicja-Kainos commented on nhais/outbound/state/work_description.py
> +        raise ValueError('Expected persistence store to not be None')
done

2020-05-05 09:14 UTC, Alicja-Kainos commented on nhais/outbound/state/work_description.py
> +        Attempts to publish the local state of the work description to the state store, checks versions to avoid
@mattd-kainos, @bartek-sarul , what do you think about it, any ideas? should we store the version in the table or do the versioning other way?

2020-05-05 09:16 UTC, grzegorz-robak commented on nhais/outbound/state/work_description.py
> +        Attempts to publish the local state of the work description to the state store, checks versions to avoid
Sure, my point wasn't to make versioning, but if it doesn't do that then remove versioning from description :)

2020-05-05 09:28 UTC, Alicja-Kainos commented on nhais/outbound/state/work_description.py
> +        Attempts to publish the local state of the work description to the state store, checks versions to avoid
removed XD

2020-05-05 09:29 UTC, grzegorz-robak approved these changes

2020-05-05 11:31 UTC, mattd-kainos requested changes
Will need to be merged to integration-adaptor-nhais instead

2020-05-06 07:48 UTC, Alicja-Kainos commented
changes moved to separate nhais repo;
nhais module from integration-adaptor repo is removed int this pull request (https://github.com/nhsconnect/integration-adaptors/pull/244#pullrequestreview-406372033)

2020-05-06 07:48 UTC, closed without merging