NIAD-237: Mongodb persistence adapter
nhsconnect/integration-adaptors pull request #249
Opened 2020-05-12 13:33 UTC by bartek-sarul

2020-05-12 15:29 UTC, mattd-kainos commented on common/persistence/mongo_persistence_adaptor.py
> +"""Module containing functionality for a DynamoDB implementation of a persistence adaptor."""
should be mongo not dynamo

2020-05-12 15:35 UTC, petervdm submitted a review, later dismissed

2020-05-12 15:35 UTC, petervdm commented on common/persistence/dynamo_persistence_adaptor.py
>  """Module containing functionality for a DynamoDB implementation of a persistence adaptor."""
These should be done in the new common repo

2020-05-12 15:35 UTC, petervdm commented on common/persistence/dynamo_persistence_adaptor.py
>  """Module containing functionality for a DynamoDB implementation of a persistence adaptor."""
Do you want to hook up that common repo as part of this?

2020-05-12 15:35 UTC, petervdm commented on common/persistence/mongo_persistence_adaptor.py
> +"""Module containing functionality for a DynamoDB implementation of a persistence adaptor."""
MongoDb

2020-05-12 15:35 UTC, petervdm commented on common/persistence/mongo_persistence_adaptor.py
> +        Constructs a DynamoDB version of a
MongoDb

2020-05-12 15:35 UTC, petervdm commented on common/persistence/mongo_persistence_adaptor.py
> +        :param strongly_consistent_read: https://docs.amazonaws.cn/en_us/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html
Probably not relevant to this?

2020-05-12 16:15 UTC, mattd-kainos commented
Haven't had a chance to get through it all yet. Would be good to update the docs on how to run and test using mongo instead of dynamo.

2020-05-12 16:22 UTC, mattd-kainos commented
Also have we thought about ensuring both are tested. Should we run component tests for both? Want to make sure there is not regression in the adaptor not being used as often.

2020-05-12 16:23 UTC, mattd-kainos requested changes
Mostly questions about config and preventing regression. Haven't tried to run locally yet.

2020-05-13 06:13 UTC, bartek-sarul commented
> Also have we thought about ensuring both are tested. Should we run component tests for both? Want to make sure there is not regression in the adaptor not being used as often.

I'll add tests that will run same set of tests on all adaptors

2020-05-13 06:14 UTC, bartek-sarul commented
> Would be good to update the docs on how to run and test using mongo instead of dynamo.

I'll update config

2020-05-14 07:41 UTC, petervdm commented on common/persistence/dynamo_persistence_adaptor.py
>  """Module containing functionality for a DynamoDB implementation of a persistence adaptor."""
Will do in a new ticket

2020-05-14 07:45 UTC, mattd-kainos commented on common/persistence/dynamo_persistence_adaptor.py
> +        self.region_name = 'eu-west-2'
I don't think this should be hardcoded.

2020-05-14 08:03 UTC, mattd-kainos commented on integration-tests/integration_tests/integration_tests/db/dynamo_wrapper.py
> +class DynamoWrapper:
Consider defining an interface for these wrappers

2020-05-14 08:09 UTC, mattd-kainos requested changes
Just one concern about the hardcoded AWS region that could cause headaches in the future. Optional improvement for wrapper interface - mostly for better autocomplete etc for devs in IDEs

2020-05-14 09:03 UTC, grzegorz-robak requested changes

2020-05-14 09:03 UTC, grzegorz-robak commented on common/persistence/mongo_persistence_adaptor.py
> +        return data
These methods are duplicated in each persistence adaptor

2020-05-14 09:03 UTC, grzegorz-robak commented on common/persistence/persistence_adaptor.py
> +def validate_data(primary_key: str):
I'd name it like `data_without_field` or `data_without_key` as `validate_data` is ambiguous, when it does just one thing.

2020-05-14 09:03 UTC, grzegorz-robak commented on common/persistence/persistence_adaptor_factory.py
> +    'mongodb': MongoPersistenceAdaptor,
option to set DynamoDB explicitly should be added also

2020-05-14 09:03 UTC, grzegorz-robak commented on integration-tests/integration_tests/integration_tests/db/dynamo_wrapper.py
> +            region_name='eu-west-2',
hardcoded region

2020-05-14 09:03 UTC, grzegorz-robak commented on mhs/spineroutelookup/Pipfile
> +ldap3 = "~=2.6"
that is different value than in integration tests

2020-05-14 11:03 UTC, mattd-kainos commented on common/persistence/dynamo_persistence_adaptor.py
> +        self.region_name = config.get_config('MHS_CLOUD_REGION', 'eu-west-2')
Should just be 'CLOUD_REGION'. config will strip the MHS_ prefix

2020-05-14 11:20 UTC, mattd-kainos submitted a review, later dismissed

2020-05-14 13:48 UTC, grzegorz-robak approved these changes

2020-05-14 13:48 UTC, grzegorz-robak submitted a review, later dismissed

2020-05-14 17:22 UTC, bartek-sarul commented
Force merge as PR has been approved before build fixes

2020-05-14 17:22 UTC, merged