Update docker-compose with override ports and correcting variable ssl…
nhsconnect/integration-adaptors pull request #250
Opened 2020-05-13 09:24 UTC by Broom94

… to true for inbound to work, readMe updated

2020-05-13 10:04 UTC, Alicja-Kainos submitted a review, later dismissed
Works for me locally :) Approved!

2020-05-13 12:42 UTC, petervdm requested changes

2020-05-13 12:42 UTC, petervdm commented on mhs/running-mhs-adaptor-locally.md
>  * Run the `./build.sh` script found in the top level directory of this project. This will build the follwoing docker containers which
Can you correct this spelling mistake please? `follwoing`

2020-05-13 13:07 UTC, Alicja-Kainos submitted a review, later dismissed

2020-05-14 12:50 UTC, Alicja-Kainos approved these changes

2020-05-14 13:43 UTC, Alicja-Kainos requested changes
could you please try execute locally the  Rest Client request collection? It seems that only healthchecks for outbound and inbound are fine

2020-05-15 07:12 UTC, Alicja-Kainos approved these changes

2020-05-18 10:26 UTC, petervdm approved these changes

2020-05-18 10:27 UTC, merged